# Other Storynotes collections

This work is just one of several storynotes collections compiled as part of the process associated with my finding and developing stories, both traditional tales *and* historical tales.

Other online storynotes collections, some of which may also appear in print at some point, include, but are not limited to, the following.

- __Island Storynotes__
  - *A Legend of Godshill*
  - *A Legend of Puckaster Cove*
  - *A Legend of Pepperpot*
  - *A Legend of Newtown*
  - *A Shanklin Tale: The Three Little Pigs*
  - *On the Loss of the Eurydice*
  - *Immorality and Vice in 1850s Newport*
  - *Young Mr Hambrough and the Ardlamont Affair*
  - *The Spithead Mutiny*
  - ... contact the author for forthcoming titles...

- *On the trail of the Sin-Eater*
- __Protest Days, Rebellion Nights__
  - *The Tale of Benjamin Topham*
  - *The Tale of James Towle*
  - ... contact the author for forthcoming titles...

- __Traditional Tales (Variants)__
  - *Hudden, and Dudden, and Donald O'Neary*
  - *The Blacksmith and the Devil*
  - *The Raggle Taggle Gypsy*
  - *Godmother Death*
  - ... contact the author for forthcoming titles...

Please contact the author for more information about how to get hold of any of these works.

Email: `monty.storyteller@gmail.com`
Web: `montystoryteller.org`

