title: A Legend of Godshill
author: Tony "Monty" Hirst
copyright: "2025" 
only_build_toc_files: true

parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    #html_copy_source: false
    latex_elements:
      papersize: a5paper
      pointsize: 12pt
      preamble: |
        % First, reset geometry options
        \AtBeginDocument{
          \date{}
          \setcounter{tocdepth}{0}
          \setcounter{secnumdepth}{0}
          \newgeometry{twoside,inner=0.9in,outer=0.5in,top=1in,bottom=1in}
          % \usepackage{fontspec}
          % \setmainfont{Palatino}
          % \setsansfont{Arial}
          % \setmonofont{Courier New}

          \clubpenalty=10000
          \widowpenalty=10000
          \displaywidowpenalty=10000
          
        }
        \usepackage{titlesec}
        \titleformat{\chapter}[display]
          {\normalfont\huge\bfseries}
          {}
          {0pt}
          {\Huge}
        \titlespacing*{\chapter}{0pt}{0pt}{40pt}

        \renewcommand{\chaptermark}[1]{%
          \markboth{#1}{}%
        }

        % size of backtick couriered font
        \renewcommand{\sphinxcode}[1]{\texttt{\footnotesize #1}}
        \renewcommand{\sphinxupquote}[1]{#1}
        
        \makeatletter
        \fancypagestyle{normal}{
            \fancyhf{}
            %\fancyfoot[RO,LE]{{\small\thepage}} % page number at bottom
            
            \fancyhead[RE]{{\small\textit{\@title}}}
            \fancyhead[LO]{{\small\nouppercase{\textit{\leftmark}}}} %chapter header

            \fancyhead[LE]{{\small\thepage}} % Page number on outside
            \fancyhead[RO]{{\small\thepage}} % Page number on outside

            \fancyfoot[LE,LO,RE,RO]{}
            \setlength{\footskip}{0pt}
            \addtolength{\textheight}{20pt}
            \renewcommand{\headrulewidth}{0.4pt} %line under header
            %\renewcommand{\footrulewidth}{0.4pt} %line over footer
          }
        \makeatother
        \fancypagestyle{plain}{
            % first page of new chapter
            \fancyhf{}
            %\fancyhead[LE]{{\small\thepage}} % Page number on outside
            %\fancyhead[RO]{{\small\thepage}} % Page number on outside
            %\fancyfoot[RO,LE]{{\small\thepage}}
            \fancyfoot[LE,LO,RE,RO]{}
            \setlength{\footskip}{0pt}
            \addtolength{\textheight}{20pt}
            \renewcommand{\headrulewidth}{0pt}
            %\renewcommand{\footrulewidth}{0.4pt}
          }
        
  extra_extensions:

latex:
  latex_documents:
    targetname: godshill.tex
  use_jupyterbook_latex: true
  latex_engine: xelatex
