
title: Folly at Folly Hall
author: Tony "Monty" Hirst
copyright: "2025" 
only_build_toc_files: true

parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    #html_copy_source: false
    latex_elements:
      papersize: a5paper
      pointsize: 12pt
      preamble: |
        \input{../../th_custom_preamble.tex}
        
  extra_extensions:

latex:
  latex_documents:
    targetname: folly_at_folly_hall.tex
  use_jupyterbook_latex: true
  latex_engine: xelatex
