# Nineteenth Century Tourist Guide Descriptions

Since the late seventeenth century, tourist guides and itineraries have featured the Isle of Wight as a well-regarded destination. Many of these guides provided descriptions of the island towns and villages as they were at the time, as well as commenting on notable attractions and scenery, and, on occasion, local legends.

Black's *Picturesque Guide to The Isle of Wight* from 1876 paints the following picture of Godshill:

> This, the "most romancy" (as old Aubrey would say) of the island-villages, abounds in bloom and leafiness, out of whose balmy depths rises the rugged church-crested hill, its abrupt sides studded with irregular cottages, and broken into flowery rifts and chasms. The Church, dedicated to All Saints, is worth a visit, as well on account of its architectural merits and interesting memorials, as of its admirable and striking position. A panorama, only to be described by a poet, greets the spectator's eye from this insulated point. "To the north the gaze embraces the whole of the vale of Newchurch, with the undulating ridge of the chalk downs beyond, ending towards the valley of the Medina in the abrupt slope of St. George's Down. The white cliff of Culver are just descried over some rising ground to the right; to the left we have the ridge separating the valleys of the Yar and Medina, and the bold line of chalk downs which here take a due southerly direction. To the south the view is more varied. The northern front of the southern chalk range, with its bold projecting spurs, and sinuous valleys lies before us. Appuldurcombe, or Week Down, with its shattered obelisk, bold wall of cliff (the northern face of the firestone stratum, which gives its picturesque character to the Undercliff), and rich hanging woods, rising immediately in front over the scattered houses and leafy knolls of the village; to the west is the huge mass of St Catherine's, marked by the twin pharoses, and the slender Alexandrian pillar; to the east rises the more picturesque outline of Shanklin Down, with its belt of timber half concealing its cliffs, on the summit of which stands the modern ruin of Cook's Castle" — *(Venables).*

A brief history of the church is also provided, including a reference to a famous lightning strike and a mention of the legend regarding the building of the Church:

> Godshill was one of the six churches with which William Fitz-Osbert, after the Norman Conquest, endowed his favourite abbey of Lire, in Normandy. Charles I presented it to Queen's College, Oxford. It was much injured by lightning in January 1778. A tradition (of no uncommon character) attempts to account for the peculiar name of the village. Its builders first proposed to erect it at the foot of the hill, but every morning found the preceding day's work undone, and their material carried to the summit. After a few days' perseverance they wisely resolved to struggle no longer against the invisible workmen, and built the church on the site indicated by the spirits, where it still stands — to all the country side around a stately beacon of the Christian faith.

Barber's *Picturesque Illustrations of the Isle of Wight*, published in 1850, describes Godshill a little more succinctly as *"a picturesque village, much remarked for the bold position of its Church, which, standing on a very abrupt hill, surrounded by the cottages of the inhabitants, may be supposed to have given name to the place, from its erection on so commanding a site"*. The legend is then described as a *[r]ustic tradition* that related how *"a more lowly spot was first selected for the erection of the church; but that the materials employed for that purpose, day by day, being regularly removed by invisible agents to the summit of the hill during the night, the workmen at length wisely determined to save themselves further unnecessary trouble, and built the church where some supernatural authority so plainly intimated that it must be erected.*

Cox's *Isle of Wight: its churches and religious houses* published in 1911, gives the legend as follows:

> An old legend, still current in the parish and district, tells how the inhabitants, when first Christian preaching had won them to the true faith, began to build a church on a level place a mile to the south-west of the present village, but as fast as they laboured during the day, when nightfall came the stones mysteriously disappeared, and were at last found on the top of the hill. Recognising that this must be the will of God, they decided that the church was to be completed on this lofty site, and from that time both the church and the village, which grew up around it, have been known by the name of Godshill.

An even more religious telling is provided in "The Isle of Wight" by George Clinch, published in 1908, quoting an *"ancient legend which is thus given in a local guide-book"*:

> The people of this village, having long lived in pagan darkness, were at length visited by a holy man who came and lived among them. He told the wondrous story of Divine self-sacrifice, and taught the Catholic religion of love and mercy. This so touched the hearts of the people that they cast down their blood-stained altars and acknowledged the true God.  
>  
> Then cried the elders of the village: "We will build a temple to His honour, where we and our children's children may worship, and by which generations yet unborn may know how the Saxon reverenced God."  
>  
> They chose, therefore, a level place, and all day long they wrought and toiled, and when night came they rested from their labours. But on the morrow, when borne during the night by invisible hands to the top of a round knoll.  
>  
> When the people saw this marvellous sight they cried with one voice: "Let us build now on the top of the hill, for this must be the will of God," and from that time the church and village have been known as Godshill in memory of this great deed.

Clinch goes on to describe how *[t]his legend, which may have been invented in explanation of a rather remarkable name, belongs to a class of which numerous examples still linger in England"*:

> Usually one finds them in places where the parish church stands at a considerable distance from the village, and, generally, they are to the effect that the building erected in or near the village during the day-time was conveyed by evil influences to a remote situation at night. The Godshill legend is a variant of this group.

```{=latex}
\let\thefootnote\relax\footnotetext{\textit{Original copies of the above works can be found in the Castle Museum library at Carisbrooke Castle. The collection is viewable by appointment.}}
```
