# Abraham Elder's Tales and Legends of the Isle of Wight

One of the few purported 19th century collections of Isle of Wight folk-tales is Abraham Elder's *Tales and Legends of the Isle of Wight*, first published in 1839. The tales are presented as if in a dialogue between the author, and his traveling companion around the island, a certain Mr Winterblossom.

According to a correspondent in the Isle of Wight County Press, a newspaper that continues to be published to this day, of Saturday 16 December 1893, [p2](https://www.britishnewspaperarchive.co.uk/viewer/bl/0001960/18931216/025/0002), *Abraham Elder produced in that year [1839] two issues of his "Tales and Legends."*

> The first issue was a small book of 196 pages with only four illustrations, drawn, I conjecture, by Abraham Elder himself. The illustration for page 4 has the curious blunder of the number 116 being substituted for 4. This smaller issue is called on the title page "Part the first." This issue has a value of its own, as it contains as a frontispiece a view of the Needles, showing the original needle rock. This frontispiece may have been meant by Abraham Elder to be included amongst the legends of the Isle of Wight. In the same year came out the second issue of the "Tales and Legends." This issue is a much larger volume, it contains 336 pages, with 14 large and 11 small woodcuts by Robert Cruikshank. The illustration of page 4 of the first issue is reproduced as a vignette on page 8 of this second issue, otherwise the 25 illustrations are entirely different from the illustrations of the first issue. Of this second issue a second edition appeared in 1843, but in no way differing from first edition.
> ...
> R. G. D.

Elder used the preface of the book to provide some background, or so we are led to believe, for the provenance of the stories in the collection. In so doing, he also reveals that he is not an Islander himself:

> It may appear singular that the present little volume, intended to illustrate the antiquities and traditions of the people of the Isle of Wight, should come from the pen of a stranger; and that the tales it contains should have been collected during the space of a short summer ramble. Fortune, however, has favoured me much, and I take this opportunity of returning my thanks to my friend, the well-known and justly celebrated antiquary, Mr. Winterblossom, for his most valuable contributions, without which this collection of Tales and Legends would have been but chaff.

Rather unusually,  Mr Winterblossom's credentials are proved by what he has *not* achieved, specifically, publishing a collection of tales himself:

> I must confess that I am rather a collector, compiler, or editor; though vanity (as some would term it) has induced me to call myself the author of the present work. I am but the wisp of straw that ties the fagot together. But it is not altogether vanity in me either: for I have repeatedly, though in vain, urged Mr. Winterblossom to undertake the task. But he said that he had once spent many years and infinite labour in preparing a work of deep erudition for the press. The public was ungrateful, and the work still remains unsold. Printer's ink he would never meddle with again; and then, added he with emphasis, taking me by the arm, "the printer will be paid, whether the work sells or not".

We also get a hint from the preface that if the current work meets with some success, Elder would happily produce a second volume:

> Should, however, the public act with greater indulgence in the present instance, it is my intention, if life and health be preserved to me, to offer a second volume to its notice in the due course of time. One difficulty presents itself.

To compile such a work, however, Elder suggests he would benefit from local assistance in sourcing or uncovering local tales. Notably, he gives a local bookseller as one of his contact addresses.

> Being a stranger to the island, — during the short time I may be able to bestow upon a visit next summer, I may perhaps overlook many things that ought to be recorded with care. I should therefore feel under obligation to any one who will call my attention to any antiquity, tale, or tradition connected with the island; — directing their communication to A. Elder, Esq., author of " Tales and Legends of the Isle of Wight," under cover to his publishers, Messrs. Simpkin, Marshall, and Co., or to Mr. French, bookseller, Newport.

Although a second *volume* of tales did not appear, a second *edition* of *Tales and Legends* was published in 1843. This edition contained several additional tales that had also appeared throughout 1839 and 1840, in the literary magazine *Bentley's Miscellany*. The first editor of *Bentley's Miscellany*, which was first published in 1836, is perhaps better known today as an author in his own right: a certain Mr. Charles Dickens, whose book *Oliver Twist* was originally serialised in that magazine. Dickens, who was born in Portsmouth, is known to have visited the Island in September, 1838, and returned again for a longer stay in the summer of 1849. It is interesting to speculate whether he had met up with one of his contributing authors on that earlier visit. As the following letter from volume one of *The Pilgrim Edition* of *The Letters of Charles Dickens* shows, Dickens' mind was at least partly on the job even if he was on holiday, although he was, perhaps, looking forward to getting home?!

> To Richard Bentley, [10] September [1838]
> *Ventnor, Isle of Wight. | Monday Evening, Septr. 9th*
> My Dear Sir,
> I have received a letter with some double or treble postage tacked to it from one "Omega" *[an unidentifed contributor whose to the Miscellany had been declined in Notices to Correspondents in April, 1838]* relative to some german translations. This Omega is an impertinent gentleman who has done me the favour to write a continuation of Pickwick and ask me to father it. In case you should hear from him again, I think it best to let you know that I have written him a reply, stating that I do not wish to accept his papers, firstly because the greater part of them are too long, and secondly because you do not require translations from new Contributors — the strong probability being (this I have *not* told him) that they have appeared somewhere else before.
> 
> I shall be home, please God, on Wednesday Evening. Shall I see you this week?
> 
> Faithfully Yours
> 
> Charles Dickens

The tale of the Godshill legend, included in this volume, was originally published in *Bentley's Miscellany*.

## Who Was Abraham Elder?

In 1873, scholarly story collector Joseph Jacobs' published *More English Fairy Tales*, his second collection of English fairy tales. The volume included a version of Elder's legend relating to the Pied Piper of Newtown, a story that appears to have made its first appearance in *Tales and Legends of the Isle of Wight* in 1839.

Whether the legend was a "true" one is a story for another day, but the publication of tale brought some attention as to who the real author might actually be, Abraham Elder having been identified as a *nom de plume*.

In the August 30th, 1873, issue of *Notes & Queries*, [Vol 12 Iss 296](https://archive.org/details/sim_notes-and-queries_1873-08-30_12_296/page/168/mode/2up), a 19th century periodical, published weekly since November 3rd, 1849, which acted as a _"Medium of Intercommunication for Literary Men, Artists, Antiquaries, Heralds"_, the following query appeared:

> "TALES AND LEGENDS OF THE ISLE OF WIGHT: with the Adventures of the Author in search of Them." By Abraham Elder, Esq. 2nd edition, 1843.— Who wrote this work? It is not mentioned in Mr. Olphar Hamst's *Handbook*. Mr. Abraham Elder was evidently a person of culture and research, possessed of a delicate humour and much literary skill. His book is very interesting, and might well be reprinted. ...
> A. J. Munby.  
> Temple.

It seems the question went unanswered.

The same question was asked by the Isle of Wight County Press correspondent *R. G. D.* in 1893:

> I have tried to find out the real name of Abraham Elder. I have learned that he either was native of, or lived in, Shanklin and that to his parents he owed the name of Clayton, but I have not yet been able to find out what name was given him by his godfather and godmother. I should be much obliged to any of yours readers who would give me this information.

In reply was a letter that just missed making it into the next week's edition who is makes some uncertain suggestions as to the identity of the mysterious author:

> ABRAHAM ELDER
>
> *To the Editor of the Isle of Wight County Press.*
>
> Sir,— Abraham Elder's "Tales and Legends of the Isle of Wight" contains a great deal of matter which has but little relation to, and which is by no means the natural product of, the Island, but which originated only in the fertile imagination of A. E., whose *real* name is shrouded in mystery, like the name of the builder of the pyramids. For years I have vainly endeavoured to discover it and still like Junius, *stat nominis umbra*. I do not think he was a native of the Island, but probably a visitor, or some one who had been resident for some time. I have heard the names of Clayton, Moreton, and others mentioned in connection with the tales, but nothing of satisfactory nature giving any real clue to the writer's identity.

The correspondent also reviews the publication history of Elder's work and passes comment on what they know of contributors to Bentley's magazine:

> The second part of the "Tales and Legends" first appeared in the pages of *Bentley's Miscellany* in 1839 and 1840. I knew one of the earliest contributors to *Bentley*, and the last survivor of that brilliant circle of writers, a gentleman who was well acquainted with most of the contributors to the earlier volumes of the *Miscellany*, and through him I made inquiries few years ago of Bentley and Son to the real designation of A. Elder, but could obtain no reply, after much research. His identity was forgotten and remained unknown to his publishers. The first part of the tales, as your correspondent "R.G.D." observes, was published in 1839, with four plates in lithograph.

The correspondent also seems to be of a different opinion to R.G.D. as to when the second issue of *Tales and Legends* was first published:

> Another issue was published in 1841, with plates by R. Cruickshank, engraved by the "gypsographic" process. In this volume the second part of the tales was first published as a book, and with the first part makes a volume in 12mo of 336 pages. A second edition appeared in 1843, and is simply reprint of the volume published in 1841. All the editions are now become scarce, the first especially.— I am, yours truly,
>
> W. H. Long. 120, High-street, Portsmouth, December 22, 1893.

However, a response that did make it in time to be included in the [Saturday 23 December 1893](https://www.britishnewspaperarchive.co.uk/viewer/bl/0001960/18931223/040/0003) edition of the *Isle of Wight County Press*, p3, was more certain of Abraham Elder's identity:

> ABRAHAM ELDER.
>
> To the Editor of the Isle of Wight County Press. Sir,
>
> In reply to the inquiry of your correspondent R.G.D., I can state that author of the "Tales and Legends of the Isle of Wight" was the late Hon. Augustus Moreton, M.P. for Gloucestershire, who wrote the book under the name of Abraham Elder when living with his uncle, Col. Moreton, about that time at Bembridge. —Yours truly. W.W. Osbourne, Bembridge, IW., Dec. 21. 1893

It seems the Editor of the Isle of Wight County Press was happy to assertion, as we can tell from an Editor's comment added to Mr Long's delayed reply in the edition of a week later:

> [Mr. Long’s letter reached us too late for insertion in our last issue, in which, it will be remembered, it was asserted on the authority of Mr. W. W. Osborne that the author of the book in question was the Hon. A. Moreton.—ED. *I.W.C.P.*]

Born in June, 1804, the Hon. Augustus Henry Moreton Macdonald of Largie (born Augustus Moreton) was the younger brother of Henry Reynolds-Moreton, 2nd Earl of Ducie, and son of Thomas Reynolds-Moreton, 1st Earl of Ducie, and Lady Frances, daughter of Henry Herbert, 1st Earl of Carnarvon. He was elected as a Member of Parliament for Gloucestershire West in 1832 and then for Gloucestershire East between 1835 and 1841. A campaigner for homeopathy, he had published various works under his own name, including *Civilisation, or, a Brief Analysis of the Natural Laws that Regulate the Numbers and Condition of Mankind* in 1836 and *Thoughts on the Corn laws, addressed to the working classes of the county of Gloucester* in 1839.

If we accept W.W. Osbourne's suggestion that Abraham Elder was, in fact, the Hon. Augustus Moreton, M.P, a claim mildly supported by W. H. Long's suggestion of possible names, then what evidence can we find of the honourable gentlemen on the island?

From a brief mention in [*A History of the County of Hampshire*: Volume 5, ed. William Page (London, 1912](https://www.british-history.ac.uk/vch/hants/vol5/pp156-170), we can probably vouch that his uncle did indeed live on the Island:

::: {pagebreak}
:::

> Bembridge.
>
> In 1854 Colonel the Hon. Augustus John Francis Moreton by his will, proved 5 September, left £300, the interest to be given to deserving poor. The legacy was invested in £327 5s. 8d. consols, producing £8 3s. 8d. yearly.

We also see from a news report in the *Hampshire Telegraph* of [Monday 19 October 1835](https://www.britishnewspaperarchive.co.uk/viewer/bl/0000069/18351019/006/0002), p2, that uncle and nephew were active in local good works:

> Public Meeting of the Inhabitants of Bembridge, held at the Free School, on Monday the 12th of October, 1835.
>
> Honourable A. MORETON, M.P. Chairman
>
> Proposed by Mr. John DENNET, and seconded by John Newman:
> 1. That this meeting deeply sensible of the important and valuable assistance rendered to the Education of the Children of the Poor by the Rev. Sir Henry Thompson, Bart. in not only erecting the School House at his own expense, and paying the salaries of the School Master and Mistress, but also for his unwearied personal attention to the moral and religious instructions of the Inhabitants generally, do hereby tender him, their grateful thanks, and express their grateful and sincerest wishes for his future welfare and happiness.
>
> ...
>
> 3. That a Committee be formed, consisting of: The Hon. Colonel Moreton, the Hon. Augustus Moreton, ...
>
> ...

We also have evidence of Moreton's social standing on the Island, as noted in this report from the *Hampshire Advertiser* of [Saturday 07 June 1845](https://www.britishnewspaperarchive.co.uk/viewer/bl/0000494/18450607/034/0008), p8:

> Cowes, Saturday June 7
>
> Royal Yacht Squadron Intelligence  
> Arrivals
>
> June 3 *Elizabeth* Hon Augustus Moreton, from Guernsey
>
> Fashionable Arrivals. The following are among members of the R. Y. S. who have visited the Squadron House during the week: ..., Hon. Augustus Moreton, ...