---
number: false

---
# Preface

When approaching the village of Godshill, on the Isle of Wight, using the road from nearby Shanklin, you might not realise there is a Church in the village at all. If making your way up from Whitwell, a glance across the fields will reveal the Church arising above what looks like a small copse of trees, before it disappears out of sight again. And for visitors arriving via the Newport road will catch a glimpse of the Church ahead of them, before losing sight of it altogether as they enter the village.

If you do manage to escape the clutches of the tea rooms and the miniature village, and make your way up the hill past what was in recent times a chocolatier's shop, you will find a much quieter old village, and the Church itself.

How the Church came to be up there on the top of the hill is a matter of legend, and this short volume brings together several different tellings of it, pulled from the archives: a tall tale from the pseudonymous Abraham Elder (1839), a poetical version from Percy G. Stone (1912), and several tourist guide versions dating back to the nineteenth century.

The volume also includes a contemporary retelling based on Abraham Elder's tall tale that I have told as part of the *'Tis Tales* set, *Island Tales*, and a brief background note regarding the possible identity of Abraham Elder.

As with many local tales and legends, they are best served told. For the traditional author of written works, the story, as much as the published work, whether a printed book, a digital e-book, an audio book or even just an extract in a Sunday supplement, is often something to be protected, something that remains under the ownership of the author to license and "perform" as they see fit. But for the traditional storyteller, the product *is* the performance. The stories are *passed on*, free to be retold by those who heard them, under common, public ownership. Whilst in one sense this volume is a written collection that can be read, my greater hope is that it provides you with a tale that you can tell on, perhaps even as you visit the village of Godshill itself.

--Tony "Monty" Hirst  
Apse Heath, September 2022.

```{=latex}
\let\thefootnote\relax\footnotetext{To keep up to date with traditional storytelling events and activities on the Isle of Wight, make sure you check the `Tis Tales website — tistales.org.uk — regularly. For more storynotes publications, please vist montystoryteller.org}
```
