# Puckaster Cove Fairy Tale

*This was my original — in the sense of first attempt at — retelling Abraham Elder's Puckaster fairy tale. If you go round the coast from Ventnor towards St Catherine's Point, you'll come to Binnel Bay, and Puckaster Cove. Now as I'm sure you all know, Puck, or pooka, is an old English word meaning "goblin" or perhaps, fairy. And that gives a clue as to the nature of this tale. Now, back in the twelfth century, there were no real roads around that part of the island, but there were footpaths, parts of which remain to this day. Pilgrims would land at Puckaster Bay and make their way up the cliff and along the Cripple Path, pass by Niton and go up to the holy well at Whitwell; and then they'd return along St Radegund's path, back to Puckaster Cove. A twelfth century circular walk, if you will.*

As you might expect, these paths could be treacherous, particularly at night, and about a mile from the cove there was a place that was, by turn, marshy, and boggy, and bordered by brambles. And at night, over that place, could often be seen Jack o'Lanterns, will-o-the-wisps, warning away the unwary. But in the midst of that inhospitable place was a wide, flat green space, and if you ever had chance to look at it, you'd likely as not be able to see fairy rings there. For that was the place where King Puck, the king of fairies, would hold court.

Now, one time, John Kann, who lived not far from the fairy rings, was chatting to one of his friends who lived nearby with his family, and who was due to be married. "I surely need to build a new house," the man said, "for me and my new wife to live in", and he described the flat green space as being the ideal place.

"Are you mad?", said John Kann, "that's no place for the likes of you, nor me"; and he convinced his friend that to build a house there would be folly indeed and would surely invite no end of trouble; that the fairy folk would not take politely to their meeting place being invaded, that bad things would happen to the man and his wife, that their children would be replaced by changelings, and suchlike.

The man was persuaded, and found land for a house elsewhere, and when the time came for the wedding, John Kann was invited. At the end of the celebrations that night, and a fine celebration it was too, John Kann set out to follow a friend of his who'd left just a few moments earlier, with a lantern to guide the way.

John saw the light up and ahead, and started to follow it, but before long, he realised he wasn't taking the path he'd expected to take, particularly as it appeared to start to lead him through a patch of brambles; and then he realised that the light had stopped. And that it wasn't as bright as he'd thought, because he was closer to it than he thought. And that he was stood on the ground that his friend had wanted to build his house on. The fairy ground. And then, he heard something. It sounding like singing, or, no, a chant:

> John Kann, is a very nice man,  
> He's a very nice man, is Mr John Kann.

And John looked around. And saw nothing.

And then he looked down. And he saw people. Tiny people. Tiny people dancing around and singing, chanting:

> John Kann, is a very nice man,  
> He's a very nice man, is Mr John Kann.

Now John was taken aback by this, as you might be, particularly because the tiny folk seem to know who he was; and then they invited him to join them in the dance.

Now, John was much much bigger than they were, and he stuttered that he was afraid he might step on them, but they said "no problem, no problem at all" and two of them started to climb up his trousers carrying something between them, something, a cup, an acorn cup, and as they got closer he saw there was something in the cup. It looked like: snuff. At once, a pinch of snuff flicked into one nostril, and he sneezed, and he sneezed so strongly that his hat flew off. Then another pinch, and another violent sneeze, and he looked at his hat. It was much larger than he expected: a trick of the light maybe. Then another pinch, another sneeze, and John realised that with each pinch, with each sneeze, he got shorter, and his clothes shrank as he did, until he was just the size of one of the wee little folk.

John looked at his hat, which had fallen off with the first sneeze, and it was now much larger than him. But to replace, one of the fairies popped a new hat, a foxglove flower hat, onto his head, and pulled him into the dance.

And how they danced.

After a while, now breathless, King Puck called order. There were now many more fairies than John Kann had originally remembered seeing, and Puck called on the newcomers to report on what mischief they had been up to. For fairies are a mischievous folk and like nothing better than playing pranks, particularly at night. And with each report, the King laughed and called for the next. Until at last, one fine young fairy, flushed with enthusiasm, explained how they had managed to catch a bee.

"Splendid", called Puck, "then we shall feast well tonight", and the bee was brought in, its wings strapped to its body with fine gossamer thread. And from the bee's legs, the fairy folk collected bee bread; and from it's honey sack, they collected honey into an acorn cup, into which they added fresh dew water, and made a fine punch from it.

Now, as they did this, John Kann looked on, and he said: "I may not be as big as I was, but that is surely not enough food or drink to go round" and Puck looked at him and laughed, and said, "not as we are, maybe" and the snuff was passed round again, and the fairies made themselves, and John Kann, even smaller. And as they sneezed, their foxglove hats fell off; and they replaced them with bluebell hats. And the food that had been collected from the bee was now more than plenty enough to go round. And so they sat on the mushrooms that had started to pop up in a circle around them, and John Kann was given pride of place, sat on what seemed to him a giant puff ball, next to the king.

After they had feasted, Puck turned to John Kann and said: "'Fairies like honey, but men like money'. Is that true, John Kann, is that true?" And John said that yes, indeed, money was a good thing to have. And Puck asked him: "and do men like gold, too, the most of all?" and John said that yes, gold was surely a precious thing to behold, but that, if he were to be given any gold at all, at the size he was, that would be a trifling amount in the world of men, and ...

"Enough, John Kann, enough," said Puck, "we will thank you properly, be sure of that", and he explained to John that if he were to go down to Puckaster Cove, and search there at dawn, where the beach was land half the day, and underwater the rest, that there he would find a flat stone, with a hole right through it, a stone we perhaps know as a witch's stone today. And if he were there as the sun was rising, and if he looked through the hole in the stone, he would see, there in the sand, grains of gold too. And the gold would be there, each day, at dawn, if the tide allowed it. But that if he ever told anyone where he was getting the gold, that would be the end of it.

And with that, the puff ball under John Kann seemed to explode and he was thrown the ground, and his bluebell hat was thrown off him too... And when he looked around he saw... he saw that dawn was coming up; and next to him, he saw his hat. But not a giant hat, a normal sized hat. And of the fairies, there was no sight. Just a fairy ring of newly grown mushrooms.

Well, John got up, and brushed himself down, and wondered at the strange dream he had just had, and set to, to walk home; but as he did so, he noticed a gap in the fairy ring where his hat had been; and in the center of the ring, a burst puff ball; and next to that, a bluebell flower. And scattered around were other flower heads: foxgloves, and bluebells.

There being no-one around, John just wondered, wondered to himself whether there might be something in the story that now came to mind; about the Cove, and of the flat stone with a hole he might find there. And it was a nice morning for a walk after all. And so he went down the path, down the path to Puckaster Cove — and the tide was out – and he started to make his way along the beach, scraping it to left and to right as he made he way. And then, he saw it. A stone. A flat stone. A flat stone with a hole right through it. And as he picked the stone up, he just scuffed the sand a bit more with his shoe, a bit deeper, and looking round, self-consciously, to check no-one was watching, he lifted the stone to his eye, and peered through the hole. And he noticed something glint, something glisten, or glister, as Shakespeare might say. And, he bent down, and, and it was a grain of gold. And John Kann found himself humming, humming a tune...

> John Kann, is a very lucky man,  
> He's a very lucky man, is Mr John Kann.

And each morning, when the tide was right, and as the sun came up, John Kann would wander down to the beach, and put the stone to his eye, and then put a handful of sand in a tub he'd carry with him. And as he'd wash the sand, the gold would gather there, at the bottom of the tub. And to hide the gold, he'd collect shells, and shellfish, and place those in the tub too. And he'd effect to sell the pretty shells, the ornamental shells, by placing them in his window. And he'd sell the shellfish too. And twice a year, he'd go up to London, supposedly to sell the best of the shells, but really to sell the gold, in secret, remembering what Puck had told him about not revealing the source of his wealth. And folk would wonder about how he seemed to be able to get such a good price from a few old shells from those silly folk in London, who obviously had more money than sense.

And by and by, a particular lady of the parish, a one person newsfeed, which is to say, a well-meaning but selfless gossip, slowly weedled her way into John Kann's affections, driven in one part by his wealth, but in another by a deep seated curiosity about how he was really coming by it.

And after a while, she married him.

But still he told her nothing.

And then, one day, after weeks, after months, of being asked what he was doing, how could those shells be worth so much in London when they sold so poorly at home, she got the secret out of him.

"Just don't go around telling everyone", he told her, "or it will come to an end".

And she didn't tell everyone, to her credit. Just one or two of her closest friends. Friends who could likewise be trusted to be discreet, if not actually keep the secret.

And so it was: the next day, when John went down to the beach, with the tide out, and the dawn rising, there were a great many people down on the beach. In fact, there were people everywhere... And whilst some of them may have found a few grains of gold that day, there was none there the next. Nor on any day thereafter.

And that is the end of the story.
